apiVersion: v1
kind: Service
metadata:
  name: time-server-api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080